#!/usr/bin/env python

import sys

pkg = 'vigir_footstep_planning_widgets'
widget = 'execute_step_plan_widget'

from rqt_gui.main import Main

main = Main()
sys.exit(main.main(sys.argv, standalone=pkg+'.'+widget))

