#!/usr/bin/env python

import sys
import rospy

from vigir_footstep_planning_lib.ocs_plugin import OCSPlugin
from vigir_footstep_planning_widgets.parameter_editor_widget import ParameterEditorWidget

from PySide.QtCore import * 
from PySide.QtGui import *

if __name__ == '__main__':
    # Initialize the node
    rospy.init_node('parameter_editor')

    # Initialize Qt
    app = QApplication(sys.argv)

    gui = OCSPlugin(ParameterEditorWidget, 'parameter_editor', 3)
    gui.show()

    app.exec_()

