#!/usr/bin/env python

import sys

pkg = 'vigir_footstep_planning_widgets'
widget = 'step_interface_widget'

from rqt_gui.main import Main

main = Main()
sys.exit(main.main(sys.argv, standalone=pkg+'.'+widget))
