#!/usr/bin/env python

import sys
import rospy

from vigir_footstep_planning_lib.ocs_plugin import OCSPlugin
from vigir_footstep_planning_widgets.step_interface_widget import StepInterfaceWidget

from PySide.QtCore import * 
from PySide.QtGui import *

if __name__ == '__main__':
    # Initialize the node
    rospy.init_node('step_interface')

    # Initialize Qt
    app = QApplication(sys.argv)

    gui = OCSPlugin(StepInterfaceWidget, 'step_interface', 2, False)
    gui.show()

    app.exec_()
